import type { CliError, CliErrorCode } from "@cellarer/core";

export const CLI_EXIT_CODE = {
  SUCCESS: 0,
  USAGE: 2,
  POLICY: 3,
  CONFLICT: 4,
  EXECUTION: 5,
  RECOVERY: 6,
  INTERNAL: 70,
} as const;

export type CliExitCode = (typeof CLI_EXIT_CODE)[keyof typeof CLI_EXIT_CODE];

const ERROR_EXIT_CODES = {
  INVALID_USAGE: CLI_EXIT_CODE.USAGE,
  INVALID_INPUT: CLI_EXIT_CODE.USAGE,
  INPUT_REQUIRED: CLI_EXIT_CODE.USAGE,
  INPUT_AMBIGUITY: CLI_EXIT_CODE.USAGE,
  POLICY_VIOLATION: CLI_EXIT_CODE.POLICY,
  DOMAIN_VALIDATION_FAILED: CLI_EXIT_CODE.POLICY,
  STALE_REVISION: CLI_EXIT_CODE.CONFLICT,
  LOCK_CONFLICT: CLI_EXIT_CODE.CONFLICT,
  TARGET_CONFLICT: CLI_EXIT_CODE.CONFLICT,
  EXECUTION_FAILED: CLI_EXIT_CODE.EXECUTION,
  PARTIAL_FAILURE: CLI_EXIT_CODE.EXECUTION,
  RECOVERY_REQUIRED: CLI_EXIT_CODE.RECOVERY,
  INTERNAL_ERROR: CLI_EXIT_CODE.INTERNAL,
} as const satisfies Record<CliErrorCode, CliExitCode>;

export function exitCodeForError(error: Pick<CliError, "code">): CliExitCode {
  return ERROR_EXIT_CODES[error.code];
}
