import { describe, expect, it } from "vitest";
import { GENERATED_HEADER, isGenerated, renderRules, sourceMarker } from "../src/markers.js";

describe("markers", () => {
  it("exposes the generated-file header constant", () => {
    expect(GENERATED_HEADER).toBe("<!-- Generated by cellarer -->");
  });

  it("builds a POSIX source marker (backslashes normalized)", () => {
    expect(sourceMarker("rules/coding-style.md")).toBe("<!-- Source: rules/coding-style.md -->");
    expect(sourceMarker("rules\\win\\style.md")).toBe("<!-- Source: rules/win/style.md -->");
  });

  it("renders a single fragment with header + source marker + trimmed content", () => {
    const out = renderRules([{ relPath: "rules/a.md", content: "  Hello world  \n" }]);
    expect(out).toBe(
      "<!-- Generated by cellarer -->\n\n<!-- Source: rules/a.md -->\n\nHello world\n",
    );
  });

  it("concatenates multiple fragments separated by a blank line", () => {
    const out = renderRules([
      { relPath: "rules/a.md", content: "A" },
      { relPath: "rules/b.md", content: "B" },
    ]);
    expect(out).toBe(
      "<!-- Generated by cellarer -->" +
        "\n\n<!-- Source: rules/a.md -->\n\nA\n" +
        "\n" +
        "\n\n<!-- Source: rules/b.md -->\n\nB\n",
    );
  });

  it("renders just the header when there are no fragments", () => {
    expect(renderRules([])).toBe("<!-- Generated by cellarer -->\n");
  });

  it("detects cellarer-generated content via the header", () => {
    const out = renderRules([{ relPath: "rules/a.md", content: "A" }]);
    expect(isGenerated(out)).toBe(true);
    expect(isGenerated("  \n" + out)).toBe(true); // tolerant of leading whitespace
    expect(isGenerated("# My hand-written CLAUDE.md\n")).toBe(false);
    expect(isGenerated("")).toBe(false);
  });
});
