import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { applyScan, scanPlan } from "../src/engine/scan.js";
import type { Env } from "../src/env.js";
import { readOperationJournal } from "../src/protocol/journal.js";
import { readStoreRevision } from "../src/protocol/store-revision.js";
import {
  listMcpArtifacts,
  listRuleArtifacts,
  listSkillArtifacts,
  readMcpArtifact,
} from "../src/store/store.js";
import { ensureBaseDirs, makeTmpEnv, type TmpEnv } from "./helpers/env.js";

const REAL_TOKEN = "ghp_0123456789abcdefghijklmnopqrstuvwx";

// 建一个空库房(store/{rules,mcp,skills} 就绪)。
async function emptyStore(t: TmpEnv): Promise<string> {
  const storeRoot = t.path("home", ".cellarer");
  for (const sub of ["rules", "mcp", "skills"]) {
    await t.env.fs.mkdir(t.path("home", ".cellarer", "store", sub), { recursive: true });
  }
  return storeRoot;
}

describe("engine/scan — rules", () => {
  let t: TmpEnv;
  beforeEach(async () => {
    t = makeTmpEnv();
    await ensureBaseDirs(t);
  });
  afterEach(() => t.cleanup());

  it("imports a hand-written rules file into the store", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(t.path("home", ".claude", "CLAUDE.md"), "# My rules\nUse tabs.");
    const r = await applyScan(t.env, { storeRoot, agent: "claude-code", scope: "global" });
    expect(r.imported.map((i) => i.kind)).toContain("rules");
    const rules = await listRuleArtifacts(t.env, storeRoot);
    expect(rules.map((a) => a.name)).toContain("claude-code");
  });

  it("rejects silently wrong scan output and retains signed recovery evidence", async () => {
    const storeRoot = await emptyStore(t);
    const source = t.path("home", ".claude", "CLAUDE.md");
    const target = t.path("home", ".cellarer", "store", "rules", "claude-code.md");
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(source, "# signed scan rules");
    const rename = t.env.fs.rename;
    const env: Env = {
      ...t.env,
      fs: {
        ...t.env.fs,
        rename: async (oldPath, newPath) => {
          await rename(oldPath, newPath);
          if (newPath === target) await t.env.fs.writeFile(newPath, "silent wrong scan output");
        },
      },
    };

    const result = await applyScan(env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["rules"],
    });

    expect(result).toMatchObject({
      imported: [],
      operation: {
        ok: false,
        conflict: { code: "PARTIAL_FAILURE" },
        journal: {
          status: "recovery-required",
          actions: [
            {
              status: "failed",
              receipt: { error: { code: "ACTION_POSTCONDITION_FAILED" } },
            },
          ],
        },
      },
    });
    await expect(readStoreRevision(t.env, storeRoot)).resolves.toBe(0);
    await expect(readOperationJournal(t.env, storeRoot)).resolves.toMatchObject({
      status: "recovery-required",
    });
  });

  it("does NOT re-absorb a cellarer-generated rules file (provenance via marker)", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "CLAUDE.md"),
      "<!-- Generated by cellarer -->\n\nstuff",
    );
    const p = await scanPlan(t.env, { storeRoot, agent: "claude-code", scope: "global" });
    expect(p.items.find((i) => i.kind === "rules")).toBeUndefined();
    expect(p.warnings.some((w) => w.includes("cellarer-generated"))).toBe(true);
  });

  it("refuses to import a rules file that contains a plaintext secret (write-time backstop)", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "CLAUDE.md"),
      `# Rules\nexport GITHUB_TOKEN=${REAL_TOKEN}\n`,
    );
    const r = await applyScan(t.env, { storeRoot, agent: "claude-code", scope: "global" });
    // 自由文本无法自动脱敏 → 拒绝入库 + 告警。
    expect(r.imported.find((i) => i.kind === "rules")).toBeUndefined();
    expect(r.plan.warnings.some((w) => w.includes("secret-scan"))).toBe(true);
    // 库房没有该制品(零明文)。
    const rules = await listRuleArtifacts(t.env, storeRoot);
    expect(rules.map((a) => a.name)).not.toContain("claude-code");
  });
});

describe("engine/scan — mcp secret redaction (red line)", () => {
  let t: TmpEnv;
  beforeEach(async () => {
    t = makeTmpEnv();
    await ensureBaseDirs(t);
  });
  afterEach(() => t.cleanup());

  it("redacts secrets to placeholders BEFORE writing the store (on-disk grep: no plaintext)", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    // agent 的 mcp.json 含明文 token。
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({
        mcpServers: { ctx: { command: "npx", env: { API_KEY: REAL_TOKEN } } },
      }),
    );
    const r = await applyScan(t.env, { storeRoot, agent: "claude-code", scope: "global" });
    expect(r.imported.find((i) => i.kind === "mcp")?.name).toBe("ctx");
    // 落盘断言:库房 mcp 制品文件绝无明文真值。
    const storeFile = await t.env.fs.readFile(
      t.path("home", ".cellarer", "store", "mcp", "ctx.json"),
    );
    expect(storeFile).not.toContain(REAL_TOKEN);
    expect(storeFile).toContain("${CELLARER_SECRET:");
    // canonical 读回:env 值是占位符。
    const { server } = await readMcpArtifact(t.env, storeRoot, "mcp/ctx");
    if (server.kind === "stdio") {
      expect(server.env?.API_KEY).toMatch(/^\$\{CELLARER_SECRET:/);
    }
    // secretRefs 记在计划项里(不含真值)。
    const item = r.imported.find((i) => i.kind === "mcp");
    expect(item?.secretRefs?.length).toBeGreaterThan(0);
    expect(JSON.stringify(r.plan)).not.toContain(REAL_TOKEN);
  });

  it("imports codex TOML mcp servers (decode via adapter codec)", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".codex"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".codex", "config.toml"),
      `model = "gpt-5"\n\n[mcp_servers.gh]\ncommand = "docker"\nargs = ["run", "x"]\n`,
    );
    const r = await applyScan(t.env, {
      storeRoot,
      agent: "codex",
      scope: "global",
      capabilities: ["mcp"],
    });
    expect(r.imported.find((i) => i.name === "gh")).toBeDefined();
    const mcp = await listMcpArtifacts(t.env, storeRoot);
    expect(mcp.map((a) => a.name)).toContain("gh");
  });

  it("redacts a secret passed via args (not just env/headers)", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({
        mcpServers: { s: { command: "npx", args: ["mcp", "--token", REAL_TOKEN] } },
      }),
    );
    await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
    });
    const storeFile = await t.env.fs.readFile(
      t.path("home", ".cellarer", "store", "mcp", "s.json"),
    );
    expect(storeFile).not.toContain(REAL_TOKEN); // args 里的真值已脱敏
    expect(storeFile).toContain("${CELLARER_SECRET:");
  });

  it("refuses to import a custom-kind server whose config embeds a plaintext secret", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    // 既无 command 也无 url → custom;config 内嵌明文 token,redact 看不到结构 → 写前护栏拦。
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({ mcpServers: { weird: { type: "x", apiKey: REAL_TOKEN } } }),
    );
    const r = await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
    });
    expect(r.imported.find((i) => i.name === "weird")).toBeUndefined();
    expect(r.plan.warnings.some((w) => w.includes("secret-scan"))).toBe(true);
    const mcp = await listMcpArtifacts(t.env, storeRoot);
    expect(mcp.map((a) => a.name)).not.toContain("weird");
  });

  it("--into-collection tags imported artifacts in config.json", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({ mcpServers: { internalsrv: { command: "x" } } }),
    );
    await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
      intoCollection: "internal",
    });
    const { loadConfig } = await import("../src/store/config.js");
    const config = await loadConfig(t.env, storeRoot);
    expect(config.artifacts["mcp/internalsrv"]?.collections).toEqual(["internal"]);
  });

  it("rejects collection drift before the lock without importing or overwriting config", async () => {
    const storeRoot = await emptyStore(t);
    const configPath = t.path("home", ".cellarer", "config.json");
    const external = `${JSON.stringify({ version: 1, external: true }, null, 2)}\n`;
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({ mcpServers: { drifted: { command: "x" } } }),
    );
    const driftEnv = driftBeforeMutationLock(t.env, async () => {
      await t.env.fs.writeFile(configPath, external);
    });

    const result = await applyScan(driftEnv, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
      intoCollection: "external-drift",
    });

    expect(result).toMatchObject({
      imported: [],
      operation: {
        ok: false,
        conflict: { code: "TARGET_PRECONDITION_CONFLICT", target: configPath },
      },
    });
    await expect(t.env.fs.readFile(configPath)).resolves.toBe(external);
    await expect(
      t.env.fs.lstat(t.path("home", ".cellarer", "store", "mcp", "drifted.json")),
    ).rejects.toThrow();
  });
});

function driftBeforeMutationLock(env: Env, drift: () => Promise<void>): Env {
  const writeFileExclusive = env.fs.writeFileExclusive;
  let injected = false;
  return {
    ...env,
    fs: {
      ...env.fs,
      writeFileExclusive: async (path, data, opts) => {
        if (!injected && path.endsWith("mutation.lock")) {
          injected = true;
          await drift();
        }
        return writeFileExclusive(path, data, opts);
      },
    },
  };
}

describe("engine/scan — skills", () => {
  let t: TmpEnv;
  beforeEach(async () => {
    t = makeTmpEnv();
    await ensureBaseDirs(t);
  });
  afterEach(() => t.cleanup());

  it("imports a real skill directory but skips symlinked ones (shared pool)", async () => {
    const storeRoot = await emptyStore(t);
    const skillsDir = t.path("home", ".claude", "skills");
    await t.env.fs.mkdir(t.path("home", ".claude", "skills", "real-skill"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "skills", "real-skill", "SKILL.md"),
      "# Real",
    );
    // 一个软链 skill(模拟共享池指向别处)——不应被收编。
    const elsewhere = t.path("elsewhere");
    await t.env.fs.mkdir(elsewhere, { recursive: true });
    await t.env.fs.symlink(elsewhere, `${skillsDir}/linked-skill`, "dir");

    const r = await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["skills"],
    });
    const names = r.imported.filter((i) => i.kind === "skills").map((i) => i.name);
    expect(names).toContain("real-skill");
    expect(names).not.toContain("linked-skill");
    // 库房里有了 real-skill 真源副本。
    const skills = await listSkillArtifacts(t.env, storeRoot);
    expect(skills.map((a) => a.name)).toContain("real-skill");
    expect(
      await t.env.fs.readFile(
        t.path("home", ".cellarer", "store", "skills", "real-skill", "SKILL.md"),
      ),
    ).toBe("# Real");
  });
});

describe("engine/scan — conflict strategy + non-interactive", () => {
  let t: TmpEnv;
  beforeEach(async () => {
    t = makeTmpEnv();
    await ensureBaseDirs(t);
  });
  afterEach(() => t.cleanup());

  async function seedAgentMcp(t: TmpEnv): Promise<string> {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({ mcpServers: { dup: { command: "new-cmd" } } }),
    );
    // 库房已有同名 dup 制品。
    await t.env.fs.writeFile(
      t.path("home", ".cellarer", "store", "mcp", "dup.json"),
      JSON.stringify({ command: "old-cmd" }),
    );
    return storeRoot;
  }

  it("keep-mine: skips the conflicting artifact", async () => {
    const storeRoot = await seedAgentMcp(t);
    const r = await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
      conflict: "keep-mine",
    });
    expect(r.imported).toHaveLength(0);
    const { server } = await readMcpArtifact(t.env, storeRoot, "mcp/dup");
    if (server.kind === "stdio") expect(server.command).toBe("old-cmd"); // 库房未被覆盖
  });

  it("keep-theirs (default): overwrites the store artifact", async () => {
    const storeRoot = await seedAgentMcp(t);
    await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
    });
    const { server } = await readMcpArtifact(t.env, storeRoot, "mcp/dup");
    if (server.kind === "stdio") expect(server.command).toBe("new-cmd"); // 被收编覆盖
  });

  it("copy: creates a suffixed copy, leaving the original", async () => {
    const storeRoot = await seedAgentMcp(t);
    const r = await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
      conflict: "copy",
    });
    expect(r.imported.find((i) => i.name === "dup-claude-code")).toBeDefined();
    const names = (await listMcpArtifacts(t.env, storeRoot)).map((a) => a.name);
    expect(names).toContain("dup"); // 原件保留
    expect(names).toContain("dup-claude-code"); // 副本
  });

  it("scanPlan is read-only (writes nothing to the store)", async () => {
    const storeRoot = await seedAgentMcp(t);
    await scanPlan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["mcp"],
    });
    // store 仍只有原 dup,无新增/覆盖。
    const { server } = await readMcpArtifact(t.env, storeRoot, "mcp/dup");
    if (server.kind === "stdio") expect(server.command).toBe("old-cmd");
  });

  it("selectItems imports only the exact row when scanned names collide", async () => {
    const storeRoot = await emptyStore(t);
    await t.env.fs.mkdir(t.path("home", ".claude"), { recursive: true });
    await t.env.fs.writeFile(t.path("home", ".claude", "CLAUDE.md"), "# Team rules");
    await t.env.fs.writeFile(
      t.path("home", ".claude", "mcp.json"),
      JSON.stringify({ mcpServers: { "claude-code": { command: "npx" } } }),
    );

    const r = await applyScan(t.env, {
      storeRoot,
      agent: "claude-code",
      scope: "global",
      capabilities: ["rules", "mcp"],
      selectItems: [
        {
          kind: "rules",
          name: "claude-code",
          source: t.path("home", ".claude", "CLAUDE.md"),
        },
      ],
    });

    expect(r.imported).toEqual([expect.objectContaining({ kind: "rules", name: "claude-code" })]);
    expect((await listRuleArtifacts(t.env, storeRoot)).map((a) => a.name)).toContain("claude-code");
    expect((await listMcpArtifacts(t.env, storeRoot)).map((a) => a.name)).not.toContain(
      "claude-code",
    );
  });
});
