// 溯源标记(照抄 ruler RuleProcessor 文本格式,见计划 §7.1)。
// 用于:渲染 rules 时插入来源标记;扫描/漂移时识别「哪些是 cellarer 写的」。
import type { RuleFragment } from "./adapters/types.js";

// 所有生成文件首行都加(比 ruler 更严:不依赖弱前缀做 provenance 判定)。
export const GENERATED_HEADER = "<!-- Generated by cellarer -->";

// 路径 POSIX 化:Windows 反斜杠 → 正斜杠,保证跨平台 marker 一致。
function toPosix(relPath: string): string {
  return relPath.replace(/\\/g, "/");
}

export function sourceMarker(relPath: string): string {
  return `<!-- Source: ${toPosix(relPath)} -->`;
}

// 渲染多个 rule 片段为单一文件文本:
// header + 各节(`\n\n<!-- Source: x -->\n\n<trimmed>\n`)以 `\n` join。
export function renderRules(fragments: RuleFragment[]): string {
  if (fragments.length === 0) {
    return `${GENERATED_HEADER}\n`;
  }
  const sections = fragments.map((f) => `\n\n${sourceMarker(f.relPath)}\n\n${f.content.trim()}\n`);
  return GENERATED_HEADER + sections.join("\n");
}

// 是否由 cellarer 生成:首个非空白行是否为 generated header。
export function isGenerated(content: string): boolean {
  return content
    .trimStart()
    .replace(/^---\nalwaysApply: true\n---\n/, "")
    .startsWith(GENERATED_HEADER);
}
